AgregatorLinkow/Controllers/ProfileController.cs
using System.Threading.Tasks;
using AgregatorLinkow.Data.Interfaces;
using AgregatorLinkow.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NToastNotify;

namespace AgregatorLinkow.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly IToastNotification _toastNotification;
        private readonly ILinkRepository _linkRepository;

        public ProfileController(IToastNotification toastNotification, ILinkRepository linkRepository)
        {
            _toastNotification = toastNotification;
            _linkRepository = linkRepository;
        }

        public async Task<IActionResult> Index(int? pageNumber)
        {
            ViewData["linkList"] = await _linkRepository.GetUserLinks(pageNumber);

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("Title, URL")] Link link)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _linkRepository.Create(link);
                    _toastNotification.AddSuccessToastMessage("Successfully added new link");
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException)
            {
                _toastNotification.AddErrorToastMessage("Something went wrong");
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

AgregatorLinkow/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Link Aggregator</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/all.min.css" />
    <style>
        a { color: #343a40; }
  </style>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggler">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Link Aggregator</a>
                    <a class="nav-link text-white" asp-area="" asp-controller="Profile" asp-action="Index" title="Profile">Add new link</a>
                    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                        <li class="nav-item">
                            <partial name="_LoginPartial"/>
                        </li>
                    </ul>
                </div>
            </div>

        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Component.InvokeAsync("NToastNotify")
    @RenderSection("Scripts", required: false)
</body>
</html>